"""add transactions table and project pda wallet

Revision ID: 18c2dad13d80
Revises: 6a2f0e99f0f7
Create Date: 2026-01-31 17:06:53.997440

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18c2dad13d80"
down_revision: Union[str, Sequence[str], None] = "6a2f0e99f0f7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("investment_id", sa.Uuid(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONFIRMED",
                "FAILED",
                name="transactionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("solana_transaction_signature", sa.String(length=255), nullable=True),
        sa.Column("user_wallet", sa.String(length=255), nullable=True),
        sa.Column("pda_address", sa.String(length=255), nullable=True),
        sa.Column("solana_amount", sa.Numeric(precision=19, scale=9), nullable=True),
        sa.Column("transaction_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_attempts", sa.Integer(), nullable=False),
        sa.Column("failure_reason", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="check_positive_amount"),
        sa.CheckConstraint(
            "solana_amount IS NULL OR solana_amount > 0",
            name="check_positive_solana_amount",
        ),
        sa.ForeignKeyConstraint(
            ["investment_id"], ["investments.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_investment_id"),
        "transactions",
        ["investment_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_pda_address"),
        "transactions",
        ["pda_address"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_solana_transaction_signature"),
        "transactions",
        ["solana_transaction_signature"],
        unique=True,
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_user_wallet"),
        "transactions",
        ["user_wallet"],
        unique=False,
    )
    op.create_unique_constraint(
        "uq_user_project", "investments", ["user_id", "project_id"]
    )
    op.drop_column("investments", "amount")
    op.add_column(
        "projects", sa.Column("solana_pda_wallet", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_projects_solana_pda_wallet"),
        "projects",
        ["solana_pda_wallet"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_solana_pda_wallet"), table_name="projects")
    op.drop_column("projects", "solana_pda_wallet")
    op.add_column(
        "investments",
        sa.Column(
            "amount",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_user_project", "investments", type_="unique")
    op.drop_index(op.f("ix_transactions_user_wallet"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_index(
        op.f("ix_transactions_solana_transaction_signature"), table_name="transactions"
    )
    op.drop_index(op.f("ix_transactions_pda_address"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_investment_id"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
