"""remove wallet_address from users

Revision ID: 1cadf5eea9b8
Revises: f1bc7b55207c
Create Date: 2026-01-31 14:12:08.903507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cadf5eea9b8'
down_revision: Union[str, Sequence[str], None] = 'f1bc7b55207c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_wallet_address'), table_name='users')
    op.drop_column('users', 'wallet_address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('wallet_address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_wallet_address'), 'users', ['wallet_address'], unique=False)
    # ### end Alembic commands ###
