"""add parking lot, parcels, and parcel_id and parking_lot_id to projects

Revision ID: 47b0658513d4
Revises: 20770244d849
Create Date: 2026-01-31 15:25:35.828595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47b0658513d4'
down_revision: Union[str, Sequence[str], None] = '20770244d849'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parking_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=True),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('popular_times', sa.JSON(), nullable=True),
    sa.Column('avg_utilization', sa.Float(), nullable=True),
    sa.Column('underutilized_hours', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('user_ratings_total', sa.Integer(), nullable=True),
    sa.Column('business_status', sa.String(length=50), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('is_available_for_rent', sa.Boolean(), nullable=True),
    sa.Column('contact_notes', sa.Text(), nullable=True),
    sa.Column('estimated_capacity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parking_lots_id'), 'parking_lots', ['id'], unique=False)
    op.create_index(op.f('ix_parking_lots_place_id'), 'parking_lots', ['place_id'], unique=True)
    op.create_table('parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parking_lot_id', sa.Integer(), nullable=True),
    sa.Column('apn', sa.String(length=100), nullable=False),
    sa.Column('address', sa.Text(), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=2), nullable=False),
    sa.Column('owner_name', sa.String(length=255), nullable=False),
    sa.Column('owner_mailing_address', sa.Text(), nullable=True),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('is_likely_commercial', sa.Boolean(), nullable=False),
    sa.Column('zoning', sa.String(length=100), nullable=True),
    sa.Column('land_use', sa.String(length=255), nullable=True),
    sa.Column('lot_size_sqft', sa.Float(), nullable=True),
    sa.Column('assessed_value', sa.Integer(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('geometry', sa.JSON(), nullable=True),
    sa.Column('rentability_score', sa.Integer(), nullable=True),
    sa.Column('rentability_notes', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parking_lot_id'], ['parking_lots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parcels_apn'), 'parcels', ['apn'], unique=False)
    op.create_index(op.f('ix_parcels_id'), 'parcels', ['id'], unique=False)
    op.create_index(op.f('ix_parcels_parking_lot_id'), 'parcels', ['parking_lot_id'], unique=False)
    op.add_column('projects', sa.Column('parcel_id', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('parking_lot_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_projects_parcel_id'), 'projects', ['parcel_id'], unique=False)
    op.create_index(op.f('ix_projects_parking_lot_id'), 'projects', ['parking_lot_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'parking_lots', ['parking_lot_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'parcels', ['parcel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_parking_lot_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_parcel_id'), table_name='projects')
    op.drop_column('projects', 'parking_lot_id')
    op.drop_column('projects', 'parcel_id')
    op.drop_index(op.f('ix_parcels_parking_lot_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_id'), table_name='parcels')
    op.drop_index(op.f('ix_parcels_apn'), table_name='parcels')
    op.drop_table('parcels')
    op.drop_index(op.f('ix_parking_lots_place_id'), table_name='parking_lots')
    op.drop_index(op.f('ix_parking_lots_id'), table_name='parking_lots')
    op.drop_table('parking_lots')
    # ### end Alembic commands ###
