"""remove_parcel_id_from_projects

Revision ID: 6a2f0e99f0f7
Revises: 47b0658513d4
Create Date: 2026-01-31 15:51:16.141253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a2f0e99f0f7'
down_revision: Union[str, Sequence[str], None] = '47b0658513d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_projects_parcel_id'), table_name='projects')
    op.drop_constraint(op.f('projects_parcel_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'parcel_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('parcel_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_parcel_id_fkey'), 'projects', 'parcels', ['parcel_id'], ['id'])
    op.create_index(op.f('ix_projects_parcel_id'), 'projects', ['parcel_id'], unique=False)
    # ### end Alembic commands ###
