"""update projects: drop address, add investment_goal

Revision ID: b758169dd143
Revises: 5da18d46724a
Create Date: 2026-01-31 14:47:49.811144

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b758169dd143'
down_revision: Union[str, Sequence[str], None] = '5da18d46724a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('investment_goal', sa.Float(), nullable=True))
    op.drop_column('projects', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('address', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('projects', 'investment_goal')
    # ### end Alembic commands ###
